name: svcecanteen
description: A new Flutter application.



environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3
  simple_animations: ^1.3.4
  fit_image: ^0.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: Anisa Sans
      fonts:
        - asset: fonts/Anisa Sans.ttf

    - family: Lucida Console
      fonts:
        - asset: fonts/lucida-console.ttf

    - family: MVBoli
      fonts:
        - asset: fonts/mv-boli.ttf

    - family: Pacifico
      fonts:
        - asset: fonts/pacifico-reg.ttf

    - family: Bahnschrift
      fonts:
        - asset: fonts/BAHNSCHRIFT 8.ttf

    - family: Fredoka One
      fonts:
        - asset: fonts/FredokaOne-Regular.ttf

    - family: Pangolin
      fonts:
        - asset: fonts/Pangolin-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
